dist: trusty
language: tex
sudo: false

before_install:
  (grep -r '[[:blank:]]$$' $< && echo "Found trailing whitespace") || exit 0 && exit 1

addons:
    apt:
        packages:
          - texlive-full
          - biber
          - make
script:
  - make build

notifications:
    email: false
