dist: trusty
language: tex
sudo: false

before_install:
  (grep -r '[[:blank:]]$$' $< && echo "Found trailing whitespace") || exit 0 && exit 1
  - apt-get install -y texlive-full

addons:
    apt:
        packages:
          - biber
          - make
script:
  - make build

notifications:
    email: false
