dist: trusty
language: tex
sudo: false

before_install:
  - ls -l
  - (grep -r '[[:blank:]]$' Projektdokumentation.tex && echo "Found trailing whitespace" ) || exit 0 && exit 1
  - apt-get install -y texlive-full

addons:
    apt:
        packages:
          - biber
          - make
script:
  - make build

notifications:
    email: false
